# Name used by `npx nitro deploy`. Paths/main are generated in .output after `npm run build`.
name = "quick-brain-racer"
account_id = "4dd139e10860e0f20da0e01602ac898c"
compatibility_date = "2026-08-27"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
