/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuickBrainRacerIndexRouteImport } from './routes/quick-brain-racer/index'
import { Route as QuickBrainRacerLiveRouteImport } from './routes/quick-brain-racer/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickBrainRacerIndexRoute = QuickBrainRacerIndexRouteImport.update({
  id: '/quick-brain-racer/',
  path: '/quick-brain-racer/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickBrainRacerLiveRoute = QuickBrainRacerLiveRouteImport.update({
  id: '/quick-brain-racer/live',
  path: '/quick-brain-racer/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quick-brain-racer/live': typeof QuickBrainRacerLiveRoute
  '/quick-brain-racer/': typeof QuickBrainRacerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quick-brain-racer/live': typeof QuickBrainRacerLiveRoute
  '/quick-brain-racer': typeof QuickBrainRacerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quick-brain-racer/live': typeof QuickBrainRacerLiveRoute
  '/quick-brain-racer/': typeof QuickBrainRacerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quick-brain-racer/live' | '/quick-brain-racer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quick-brain-racer/live' | '/quick-brain-racer'
  id: '__root__' | '/' | '/quick-brain-racer/live' | '/quick-brain-racer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuickBrainRacerLiveRoute: typeof QuickBrainRacerLiveRoute
  QuickBrainRacerIndexRoute: typeof QuickBrainRacerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-brain-racer/': {
      id: '/quick-brain-racer/'
      path: '/quick-brain-racer'
      fullPath: '/quick-brain-racer/'
      preLoaderRoute: typeof QuickBrainRacerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-brain-racer/live': {
      id: '/quick-brain-racer/live'
      path: '/quick-brain-racer/live'
      fullPath: '/quick-brain-racer/live'
      preLoaderRoute: typeof QuickBrainRacerLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuickBrainRacerLiveRoute: QuickBrainRacerLiveRoute,
  QuickBrainRacerIndexRoute: QuickBrainRacerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
